# firm_core/sync_engine/qbo_clio_sync_config.py

from pydantic import BaseModel
from typing import Optional
from datetime import datetime, date


class QBOClioSyncConfig(BaseModel):
    id: int
    etag: Optional[str]
    enabled: bool
    sync_bills: bool
    sync_bills_start_date: Optional[date]
    revenue_item: Optional[str]
    expense_item: Optional[str]
    interest_item: Optional[str]
    discount_item: Optional[str]
    tax_item: Optional[str]
    secondary_tax_item: Optional[str]
    aggregate_taxes: Optional[bool]
    created_at: Optional[datetime]
    updated_at: Optional[datetime]
    failure_count: Optional[int]
    undeposited_funds_account: Optional[str]
    last_contact_sync_at: Optional[datetime]
    last_bill_sync_at: Optional[datetime]
    last_payment_sync_at: Optional[datetime]
    last_credit_note_sync_at: Optional[datetime]
    last_refund_sync_at: Optional[datetime]
    sync_trust: Optional[bool]
    sync_trust_start_date: Optional[date]
    last_trust_sync_at: Optional[datetime]
    sync_disbursement_transactions: Optional[bool]
    sync_bill_payment_trust_transactions: Optional[bool]
    hard_cost_expense_item: Optional[str]
    bill_number_prefix: Optional[str]
    soft_cost_expense_item: Optional[str]
    sync_hard_cost_expense_start_date: Optional[date]
    hard_cost_expense_account: Optional[str]
    last_vendor_sync_at: Optional[datetime]
    sync_hard_cost_expenses: Optional[bool]
    quickbooks_trust_account_mapping: Optional[str]
    trust_account_mappings: Optional[list]
    sync_firm_users: Optional[bool]
    firm_users_class_id: Optional[str]
    firm_users_start_date: Optional[date]
    last_sync_date: Optional[datetime]
    sync_status: Optional[str]
    synced_contacts_count: Optional[int]
    synced_bills_count: Optional[int]
    synced_payments_count: Optional[int]
    synced_matter_refunds_count: Optional[int]
    synced_credit_notes_count: Optional[int]
    synced_bad_debts_count: Optional[int]
    synced_hard_costs_count: Optional[int]
    synced_checks_count: Optional[int]
    primary_tax_id: Optional[int]
    secondary_tax_id: Optional[int]
    no_tax_id: Optional[int]
    primary_tax_rate_id: Optional[int]
    secondary_tax_rate_id: Optional[int]
    no_tax_rate_id: Optional[int]
    qbo_country: Optional[str]
    sync_bad_debt: Optional[bool]
    sync_bad_debt_start_date: Optional[date]
    last_bad_debt_sync_at: Optional[datetime]
    accounts_receivable_account: Optional[str]
    bad_debt_expense_account: Optional[str]
